### ISSUE TITLE
Could not find build_sysimg.jl

### ISSUE THREAD

**Issue by rgiordan** [rened/SystemImageBuilder.jl#2]
I am trying to use SystemImageBuilder, and I get the following error:

```
julia> using SystemImageBuilder
ERROR: could not open file /contrib/build_sysimg.jl
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/rgiordan/.julia/v0.3/SystemImageBuilder/src/SystemImageBuilder.jl, in expression starting on line 30
```

I installed julia using the synaptic package manager.  Here is my `versioninfo()`:

```
julia> versioninfo()
Julia Version 0.3.7
Commit cb9bcae* (2015-03-23 21:36 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU       Q 820  @ 1.73GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

Package Directory: /home/rgiordan/.julia/v0.3
```

I'd appreciate any help.

**Comment by rened** [comment]
Hm, this is odd. Could you please tell me what the following command outputs:

``` jl
joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia", "build_sysimg.jl")
```

Does that file exist (doesn't seem to)? Does the "build_sysimg.jl" file exist in some other directory in the vicinity?
These support files end up in different locations for from-source builds, `make install` builds and apparently even different locations for from-package-manager installations.
We can then try to update the logic that looks for this file.

Alternatively, a great way to install julia is the following:

``` jl
mkdir -p ~/julia
curl -s -L https://status.julialang.org/stable/linux-x86_64 | \
  tar -C ~/julia -x -z --strip-components=1 -f -
export PATH="$PATH:$HOME/julia/bin" 
```

Works on any distribution and is easily disposable. With that install `SystemImageBuilder` should work right away (both julia installs use the same installed packages).

**Comment by rgiordan** [comment]
I see, I think this is just incompatible with the julia package in synaptic.  Here's the result of that command (julia is in /usr/bin):

```
julia> joinpath(JULIA_HOME, Base.DATAROOTDIR, "julia", "build_sysimg.jl")
"/usr/bin/../share/julia/build_sysimg.jl"
```

The file `build_sysimg.jl` doesn't exist anywhere on my system, and I can see it's not in the synaptic package, either.  (I also added the [Julia releases ppa](https://launchpad.net/~staticfloat/+archive/ubuntu/juliareleases) and updated just to make sure it's not just that Ubuntu has an outdated version of julia.)

The install instructions you gave me works, but it would be nice to be able to use `SystemImageBuilder` and a package management system together so I can still get automatic updates.  What do you think?

**Comment by rened** [comment]
yes, I'd absolutely like to make it work with every possible release!

@staticfloat, do you exclude the `contrib` dir, and `build_sysimg.jl` specifically, when you build the ubuntu ppa's? Do you think you could include it? 

If there is a good reason against including it, I would revert to bundling `build_sysimg.jl` with `SystemImageBuilder`, but this might get messy with different Julia versions etc.

**Comment by staticfloat** [comment]
@rened The `contrib` directory is not installed via a `make install`, but `build_sysimg.jl` is specifically included, and I've now started including it in the PPA builds.  If all goes according to plan, builds including the files should start appearing in about 24 hours.

**Comment by rened** [comment]
@staticfloat awesome, thanks a lot!
@rgiordan could you please test this when you got time? thanks!

**Comment by rgiordan** [comment]
Looks like `build_sysimg.jl` has now showed up in `/usr/share/julia`, and I can now run `using SystemImageBuilder`.  Thanks!
