### ISSUE TITLE
Missing file userimg.jl

### ISSUE THREAD

**Issue by rgiordan** [rened/SystemImageBuilder.jl#3]
I have another problem with a file missing from the julia ppa:

```
julia> using SystemImageBuilder
julia> buildimage(targetpath = "/tmp/mytest/sys")
##  SystemImageBuilder: the following 62 packages will be included in the system image:
...
ERROR: opening file /usr/bin/../share/julia/base/userimg.jl: Permission denied
 in open at ./iostream.jl:117
 in open at ./iostream.jl:125
 in write at /home/rgiordan/.julia/v0.3/FunctionalData/src/io.jl:45
 in buildimage at /home/rgiordan/.julia/v0.3/SystemImageBuilder/src/SystemImageBuilder.jl:72
```

The file `userimg.jl` doesn't exist in that location or anywhere in `/usr/share/julia` or `~/.julia`.  This may be similar to [issue 2](https://github.com/rened/SystemImageBuilder.jl/issues/2).

**Comment by rened** [comment]
Can you please tell my how you install that PPA version? (I never used those) I will then try to reproduce and fix it on my Ubuntu installation. Thanks!

**Comment by rgiordan** [comment]
Sure, just do

```
sudo add-apt-repository ppa:staticfloat/juliareleases
sudo apt-get update
```

I'm not sure how this will interact with other julia repositories available to `apt-get`.

**Comment by rened** [comment]
Thanks, I will look into this!

**Comment by rened** [comment]
Ok, ic. Yes, the `userimg.jl` is created when running `build`, but in this case it can't be written, obviously. I need to fix the path to use a temporary file.

**Comment by rened** [comment]
Unfortunately, when Julia is installed via a package manager we can't (and don't really want to) mess with it. I added an error message for that case (tagged version 0.0.6), and ask the user to install a binary from julialang.org or build from source. 

Making it work with package manager installs would mean to have the user always invoke Julia specifying the path to the system image. Not nice, and as building one's own system images is more of a "pro" thing, I think in those cases it is ok to ask the user to install a Julia binary / build from source and use `SystemImageBuilder` with that version.

I know this is not very satisfying, but as the need for the whole `SystemImageBuilder` will go away with Julia 0.4 I think this is a reasonable course of action.

**Comment by rgiordan** [comment]
Ok, thanks for looking into it!  That sounds very reasonable, especially given that in 0.4 this will be unnecessary.  I'll switch to a manual install for now.
