### ISSUE TITLE
Deprecate in METADATA?

### ISSUE THREAD

**Issue by IainNZ** [rened/SystemImageBuilder.jl#4]
This package just caused some gnarly freeze on PkgEval on Julia 0.3, so I went investigating to see whats happening. I see its now deprecated. If you can, can you please submit a PR to METADATA.jl retroactively setting a maximum Julia version of `0.4`, e.g. `julia 0.3 0.4`, on all past tagged versions? This will prevent people `Pkg.add`ing it on 0.4, and will remove it from the online package listing.

**Comment by IainNZ** [comment]
e.g. https://github.com/JuliaLang/METADATA.jl/pull/3266

**Comment by rened** [comment]
Yes, I will deprecate it in METADATA. I will set it to a max version of 0.3 everywhere, as we do not need this any more on 0.4.

**Comment by rened** [comment]
(and sorry for the freeze)

**Comment by rened** [comment]
done: https://github.com/JuliaLang/METADATA.jl/pull/3310
